XBE_TITLE = SodiumX
GEN_XISO = $(XBE_TITLE).iso
NXDK_SDL = y
NXDK_NET = y

GIT_COMMIT_HASH := "$(shell git describe --abbrev=7 --always)"

LVGL_DIR = src/libs/lvgl
LV_CONF_PATH = "lv_conf.h"

# Include my files
SRCS += \
    $(CURDIR)/src/dash_database.c \
    $(CURDIR)/src/dash_eeprom.c \
    $(CURDIR)/src/dash_main.c \
    $(CURDIR)/src/dash_mainmenu.c \
    $(CURDIR)/src/dash_scroller.c \
    $(CURDIR)/src/dash_settings.c \
    $(CURDIR)/src/dash_styles.c \
    $(CURDIR)/src/dash_synop.c \
    $(CURDIR)/src/dash_browser.c \
    $(CURDIR)/src/dash_launcher.c \
    $(CURDIR)/src/dash_debug.c \
    $(CURDIR)/src/dash_anim.c \
    $(CURDIR)/src/dash_statusbar.c \
    $(CURDIR)/src/dash_controls_bar.c \
    $(CURDIR)/src/dash_sysinfo.c \
    $(CURDIR)/src/dash_remote.c \
    $(CURDIR)/src/dash_backup.c \
    $(CURDIR)/src/dash_context_menu.c \
    $(CURDIR)/src/dash_overlay_menu.c \
    $(CURDIR)/src/dash_keyboard.c \
    $(CURDIR)/src/dash_panel.c \
    $(CURDIR)/src/dash_settings_new.c \
    $(CURDIR)/src/dash_perf.c \
    $(CURDIR)/src/dash_backdrop.c \
    $(CURDIR)/src/dash_prerender.c \
    $(CURDIR)/src/img_sodiumx_glyph.c \
    $(CURDIR)/src/img_sodiumx_wordmark.c \
    $(CURDIR)/src/img_start_menu_pill.c \
    $(CURDIR)/src/main.c \
    $(CURDIR)/src/lvgl_widgets/confirmbox.c \
    $(CURDIR)/src/lvgl_widgets/generic_container.c \
    $(CURDIR)/src/lvgl_widgets/menu.c \
    $(CURDIR)/src/lvgl_widgets/helpers.c \
    $(CURDIR)/src/platform/xbox/platform.c \
    $(CURDIR)/src/platform/xbox/xbox_launch.c \
    $(CURDIR)/src/lvgl_drivers/video/xgu/lv_xgu_disp.c \
    $(CURDIR)/src/lvgl_drivers/video/xgu/lv_xgu_draw.c \
    $(CURDIR)/src/lvgl_drivers/video/xgu/lv_xgu_rect.c \
    $(CURDIR)/src/lvgl_drivers/video/xgu/lv_xgu_texture.c \
    $(CURDIR)/src/lvgl_drivers/input/sdl/lv_sdl_indev.c \
    $(CURDIR)/src/libs/jpg_decoder/jpg_decoder.c \
    $(CURDIR)/src/libs/sxml/sxml.c \
    $(CURDIR)/src/libs/toml/toml.c \
    $(CURDIR)/src/libs/tlsf/tlsf.c \
    $(CURDIR)/src/libs/ftpd/ftp_file.c src/libs/ftpd/ftp_server.c src/libs/ftpd/ftp.c \
    $(NXDK_DIR)/lib/net/lwip/src/apps/sntp/sntp.c \
    $(CURDIR)/src/fonts/lv_font_rubik_10.c \
    $(CURDIR)/src/fonts/lv_font_rubik_12.c \
    $(CURDIR)/src/fonts/lv_font_rubik_14.c \
    $(CURDIR)/src/fonts/lv_font_rubik_16.c \
    $(CURDIR)/src/fonts/lv_font_rubik_20.c \
    $(CURDIR)/src/fonts/lv_font_rubik_22.c \
    $(CURDIR)/src/fonts/lv_font_rubik_24.c \
    $(CURDIR)/src/fonts/lv_font_rubik_26.c \
    $(CURDIR)/src/fonts/lv_font_rubik_32.c \
    $(CURDIR)/src/fonts/lv_font_jetbrains_mono_10.c \
    $(CURDIR)/src/fonts/lv_font_jetbrains_mono_12.c \
    $(CURDIR)/src/fonts/lv_font_jetbrains_mono_14.c \
    $(CURDIR)/src/fonts/lv_font_jetbrains_mono_16.c \
    $(CURDIR)/src/fonts/lv_font_sg_10.c \
    $(CURDIR)/src/fonts/lv_font_sg_12.c \
    $(CURDIR)/src/fonts/lv_font_sg_14.c \
    $(CURDIR)/src/fonts/lv_font_sg_16.c \
    $(CURDIR)/src/fonts/lv_font_sg_20.c \
    $(CURDIR)/src/fonts/lv_font_sg_22.c \
    $(CURDIR)/src/fonts/lv_font_sg_24.c \
    $(CURDIR)/src/fonts/lv_font_sg_26.c \
    $(CURDIR)/src/fonts/lv_font_sg_32.c

CFLAGS += \
    -I$(CURDIR)/src \
    -I$(CURDIR)/src/libs \
    -I$(CURDIR)/src/fonts \
    -DLV_LVGL_H_INCLUDE_SIMPLE -DLV_CONF_PATH=$(LV_CONF_PATH) \
    -DWIN32 \
    -DBUILD_VERSION=\"$(GIT_COMMIT_HASH)\" \
    -DSDL_DISABLE_JOYSTICK_INIT_DELAY \
    -DLVGL_USE_CUSTOM_CONTROLLER_MAP \
    -DLVGL_USE_CUSTOM_KEYBOARD_MAP \
    -DDASH_FONT_SPACE_GROTESK \
    -DFTP_CUSTOM_ROOT_PATH \
    -DSNTP_SET_SYSTEM_TIME=xbox_sntp_set_time \
    -DSNTP_SERVER_DNS=1 \
    -Wno-implicit-function-declaration \
    -DMEMP_NUM_NETBUF=6 -DMEMP_NUM_NETCONN=6 \
    -DDEBUG_CONSOLE \
    -DNDEBUG \
    -O2

# Include SQLITE
SRCS += $(CURDIR)/src/libs/sqlite3/sqlite3.c $(CURDIR)/src/platform/win32/sqlite_win32.c
CFLAGS += \
    -DSQLITE_WITHOUT_MSIZE=1 \
    -DSQLITE_OS_OTHER=1 \
    -DSQLITE_DEFAULT_MEMSTATUS=0 \
    -DSQLITE_OMIT_DEPRECATED \
    -DSQLITE_OMIT_PROGRESS_CALLBACK \
    -DSQLITE_OMIT_SHARED_CACHE \
    -DSQLITE_OMIT_AUTOINIT \
    -DSQLITE_DISABLE_INTRINSIC \
    -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1

# Include XGU
XGU_DIR = $(CURDIR)/src/libs/xgu
XGU_LVGL_DRV_DIR = $(CURDIR)/src/lvgl_drivers/video/xgu
XGU_FLAGS = -I$(XGU_DIR)
XGU_DRV = \
    $(XGU_LVGL_DRV_DIR)/lv_xgu_disp.c \
    $(XGU_LVGL_DRV_DIR)/lv_xgu_draw.c \
    $(XGU_LVGL_DRV_DIR)/lv_xgu_rect.c \
    $(XGU_LVGL_DRV_DIR)/lv_xgu_texture.c
CFLAGS += $(XGU_FLAGS)
SRCS += $(XGU_DRV)
SHADER_OBJS = $(XGU_LVGL_DRV_DIR)/texture.inl $(XGU_LVGL_DRV_DIR)/notexture.inl

# Include shaders
%.inl: %.ps | fp20compiler
	@echo "[ FP20     ] $@"
	$(FP20COMPILER) $< > $@

# Include lvgl library
CFLAGS += -I$(LVGL_DIR)/
SRCS += $(shell find -L $(LVGL_DIR)/src/core -name \*.c)
SRCS += $(shell find -L $(LVGL_DIR)/src/draw -name \*.c)
SRCS += $(shell find -L $(LVGL_DIR)/src/extra -name \*.c)
SRCS += $(shell find -L $(LVGL_DIR)/src/font -name \*.c)
SRCS += $(shell find -L $(LVGL_DIR)/src/hal -name \*.c)
SRCS += $(shell find -L $(LVGL_DIR)/src/misc -name \*.c)
SRCS += $(shell find -L $(LVGL_DIR)/src/widgets -name \*.c)

include $(NXDK_DIR)/Makefile

clean_local:
	find . -name '*.obj' ! -path './libs/nxdk/*' -type f -delete
	find . -name '*.d' ! -path './libs/nxdk/*' -type f -delete
