#!/usr/bin/env python3
"""Generate pre-rendered pill/roundrect textures as C arrays.

Usage: python3 tools/gen_pills.py > src/dash_pill_data.h

The generated header contains static const uint8_t arrays in BGRA format
that can be used directly as lv_img_dsc_t data on both Xbox and desktop.
"""
import math, sys

def bgra(r, g, b, a):
    return bytes([b, g, r, a])

def render_pixel(dist, r_inner, r_outer, bg, bg_a, bc, bc_a):
    """Render a single pixel based on distance from circle center.
    Only anti-aliases the outer edge. Inner fill-to-border transition is hard."""
    def clamp(v, lo, hi):
        return max(lo, min(hi, v))

    if dist <= r_inner:
        return bgra(bg[0], bg[1], bg[2], bg_a)
    elif dist <= r_outer - 0.5:
        return bgra(bc[0], bc[1], bc[2], bc_a)
    elif dist <= r_outer + 0.5:
        cov = clamp(r_outer + 0.5 - dist, 0, 1)
        a = int(cov * bc_a)
        return bgra(bc[0], bc[1], bc[2], a)
    return bgra(0, 0, 0, 0)

def render_roundrect(w, h, radius, border_w, bg, bg_a, bc, bc_a):
    """Render a full rounded rectangle as BGRA pixel data."""
    pixels = bytearray(w * h * 4)

    cy_top = radius - 0.5
    cy_bot = (h - 1) - radius + 0.5
    cx_left = radius - 0.5
    cx_right = (w - 1) - radius + 0.5
    r_outer = float(radius)
    r_inner = r_outer - border_w

    for y in range(h):
        for x in range(w):
            dx = dy = 0.0
            in_corner = False

            if x < radius and y < radius:
                dx = x - cx_left
                dy = y - cy_top
                in_corner = True
            elif x >= w - radius and y < radius:
                dx = x - cx_right
                dy = y - cy_top
                in_corner = True
            elif x < radius and y >= h - radius:
                dx = x - cx_left
                dy = y - cy_bot
                in_corner = True
            elif x >= w - radius and y >= h - radius:
                dx = x - cx_right
                dy = y - cy_bot
                in_corner = True

            if in_corner:
                dist = math.sqrt(dx * dx + dy * dy)
                px = render_pixel(dist, r_inner, r_outer, bg, bg_a, bc, bc_a)
            else:
                in_border = (y < border_w or y >= h - border_w or
                             x < border_w or x >= w - border_w)
                if in_border:
                    px = bgra(bc[0], bc[1], bc[2], bc_a)
                else:
                    px = bgra(bg[0], bg[1], bg[2], bg_a)

            offset = (y * w + x) * 4
            pixels[offset:offset+4] = px

    return bytes(pixels)

def render_circle(diameter, color, opa):
    """Render a filled circle as BGRA pixel data."""
    pixels = bytearray(diameter * diameter * 4)
    center = (diameter - 1) / 2.0
    r = diameter / 2.0

    for y in range(diameter):
        for x in range(diameter):
            dx = x - center
            dy = y - center
            dist = math.sqrt(dx * dx + dy * dy)
            if dist <= r - 0.5:
                px = bgra(color[0], color[1], color[2], opa)
            elif dist <= r + 0.5:
                cov = max(0, min(1, r + 0.5 - dist))
                a = int(cov * opa)
                px = bgra(color[0], color[1], color[2], a)
            else:
                px = bgra(0, 0, 0, 0)
            offset = (y * diameter + x) * 4
            pixels[offset:offset+4] = px

    return bytes(pixels)

def emit_array(name, data, w, h):
    """Emit a C array + lv_img_dsc_t definition."""
    print(f"static const uint8_t {name}_data[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        print(f"    {hex_vals},")
    print(f"}};")
    print(f"static const lv_img_dsc_t {name} = {{")
    print(f"    .header.always_zero = 0,")
    print(f"    .header.w = {w},")
    print(f"    .header.h = {h},")
    print(f"    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,")
    print(f"    .data_size = sizeof({name}_data),")
    print(f"    .data = {name}_data,")
    print(f"}};")
    print()

# ── Define all pills ──

# Colors (RGB tuples)
EF_FG       = (0xd3, 0xc6, 0xaa)
EF_FG_MUTED = (0x9d, 0xa9, 0xa0)
EF_GREEN    = (0xa7, 0xc0, 0x80)
EF_BG3      = (0x41, 0x4b, 0x50)

CHIP_BG     = (0x2e, 0x38, 0x3c)
META_BG     = (0x37, 0x41, 0x45)

print("/* Auto-generated by tools/gen_pills.py — do not edit */")
print("#pragma once")
print("#include <lvgl.h>")
print()

# ── Status bar chips (height 27, radius 13) ──
# Measured from lv_obj with status_chip_style: pad 10+10 lr, 6+6 tb, font JBM12 (line_height=15)
# height = 15 + 6 + 6 = 27
chip_h = 27
chip_r = chip_h // 2

# Generate chips at various widths for FPS, temp, network, clock
# We'll generate a few fixed-width pills that cover the needed sizes
chip_widths = {
    "chip_fps":    75,  # "60 FPS"
    "chip_cpu":    80,  # "100% CPU"
    "chip_mem":    90,  # "30/64MB"
    "chip_temp":   60,  # "48°"
    "chip_net":    55,  # "FTP"
    "chip_clock":  70,  # "00:00"
}

for name, w in chip_widths.items():
    data = render_roundrect(w, chip_h, chip_r, 1, CHIP_BG, 140, EF_FG, 20)
    emit_array(f"pill_{name}", data, w, chip_h)

# ── Meta pills (height ~25, radius 12) ──
# pad 12+12 lr, 6+6 tb, font rubik12 (line_height=15 approx)
# Actual height needs measuring, using 25 for now
meta_h = 25
meta_r = meta_h // 2

meta_widths = {
    "meta_launches": 120,  # "0 LAUNCHES"
    "meta_ready":     80,  # "✓ READY"
}

for name, w in meta_widths.items():
    data = render_roundrect(w, meta_h, meta_r, 1, META_BG, 179, EF_FG, 20)
    emit_array(f"pill_{name}", data, w, meta_h)

# ── Status dot (6×6 green circle) ──
dot_data = render_circle(6, EF_GREEN, 255)
emit_array("pill_status_dot", dot_data, 6, 6)

# ── Toggle track ON (42×24, accent, full pill) ──
toggle_h = 24
toggle_w = 42
toggle_r = toggle_h // 2
toggle_on_data = render_roundrect(toggle_w, toggle_h, toggle_r, 0, EF_GREEN, 255, EF_GREEN, 0)
emit_array("pill_toggle_on", toggle_on_data, toggle_w, toggle_h)

# ── Toggle track OFF (42×24, EF_BG3, full pill) ──
toggle_off_data = render_roundrect(toggle_w, toggle_h, toggle_r, 0, EF_BG3, 255, EF_BG3, 0)
emit_array("pill_toggle_off", toggle_off_data, toggle_w, toggle_h)

# ── Toggle thumb (18×18 white circle) ──
thumb_data = render_circle(18, (0xff, 0xff, 0xff), 255)
emit_array("pill_toggle_thumb", thumb_data, 18, 18)

# ── START pill (height ~18, radius 6) ──
# pad 9+9 lr, 3+3 tb, font rubik12, radius=6
start_h = 21  # 15 + 3 + 3
start_w = 80  # "START ▸ Menu"
start_data = render_roundrect(start_w, start_h, 6, 0, EF_FG, 20, EF_FG, 0)
emit_array("pill_start", start_data, start_w, start_h)

print("/* End of generated pill data */")
